#include <stdio.h>
#define PI  3.1419
int main(){
    double yukseklik;
    double cap;
    double cap2;
    double alan;
    double hacim;
    double hacim2;
    double yaricap;
    double sayi1;
    double sayi2;
    double harmonik_ortalama;
    double gosterge1;
    double gosterge2;
    double tuketim_miktari;
    double tuketim_tutari;
    double atiksu_bedeli;
    double toplam2;
    double apsis;
    double apsis1;
    double apsis2;
    double ordinat;
    double ordinat1;
    double ordinat2;
    double carpim;
    double toplam;
    printf("ODEV1 Hazirlayan Kenan Martin Ozaltun\n------------------\n\nCOZUM 6.1:\n---------\nYuksekligi giriniz:");
    scanf("%lf",&yukseklik);
    printf("Capi giriniz:");
    scanf("%lf",&cap);
    printf("Girdi degerleri: yukseklik %lf ve cap %lf\n",yukseklik,cap);
    alan=PI*(cap/2.0)*(cap/2.0);
    hacim=alan*yukseklik/3.0;
    printf("Dairesel koninin hacmi:%lf\n---------\n",hacim);
    printf("COZUM 6.4:\n---------\n\n    .-\"-,\n   /_ _  \\ \n   \\\@ @  / \n   (_= _)\n     )(_\n    /((_')_,\"\n    \\__(/-\"\n   __|||__\n  ((__|__))\n---------\nCOZUM 6.16:\n---------\nBirinci sayiyi giriniz:");
    scanf("%lf",&sayi1);
    printf("Ikinci sayiyi giriniz:");
    scanf("%lf",&sayi2);
    harmonik_ortalama=(2.0*sayi1*sayi2/(sayi1+sayi2));
    carpim=2*sayi1*sayi2;
    toplam=sayi1+sayi2;
    printf("Harmonik ortalamasi alinacak degerler: %lf %lf\n---------------------------------------------\nHarmonik Ortalama = %lf\n---------\nCOZUM 6.22:\n---------\nIlk gostergeyi giriniz:",sayi1,sayi2,harmonik_ortalama);
    scanf("%lf",&gosterge1);
    printf("Son gostergeyi giriniz:");
    scanf("%lf",&gosterge2);
    tuketim_miktari=gosterge2-gosterge1;
    tuketim_tutari=0.912857*tuketim_miktari;
    atiksu_bedeli=tuketim_tutari/2.0;
    toplam2=tuketim_tutari+atiksu_bedeli;
    printf("------------------\nTuketim Miktari:           %lf\nTuketim Tutari:            %lf\nAtik Su Bedeli(yuzde 50):  %lf\nToplam:                    %lf\n---------\nCOZUM6.27:\n---------Ilk noktanin x1 y1 degerini giriniz(Ornegin:6 4):",tuketim_miktari,tuketim_tutari,atiksu_bedeli);
    scanf("%lf %lf",&apsis1,&ordinat1);
    printf("Ikinci noktanin x2 y2 degerini giriniz:(Ornegin:4 4)");
    scanf("%lf %lf",&apsis2,&ordinat2);
    apsis=(apsis1+apsis2)/2;
    ordinat=(ordinat1+ordinat2)/2;
    printf("x0 = %lf\ny0 = %lf",apsis,ordinat);
    return 0;
}

